### ISSUE TITLE
`bankai start` yields "TypeError: list.getEntries is not a function"

### ISSUE THREAD

**Issue by aharonw** [choojs/bankai#477]
I created a new project using npm create-choo-app. When I run `bankai start` the process begins, but the abruptly aborts with the following message:

```
A critical error occured, forcing Bankai to abort:
TypeError: list.getEntries is not a function
at parseEntries (/Users/208812/sites/open-source/node_modules/on-performance/index.js:47:10)
at Timeout._onTimeout (/Users/208812/sites/open-source/node_modules/on-performance/index.js:36:5)
at ontimeout (timers.js:427:11)
at tryOnTimeout (timers.js:289:5)
at listOnTimeout (timers.js:252:5)
at Timer.processTimers (timers.js:212:10)
```

I'm running node v10.0.0 - Am I doing something wrong?

**Comment by jekrb** [comment]
@aharonw I think there was a breaking change in node in the upgrade to 10.0.0 that is causing this.  I ran into the same issue after upgrading and went back to v9.11.1 for now. 

You're not doing anything wrong :)

**Comment by jekrb** [comment]
Yeahh looks like Node 10.0.0 removed the `.getEntries` method of `require('perf_hooks').performance`
https://github.com/nodejs/node/commit/2ec6995555

**Comment by bcomnes** [comment]
Where is bankai calling that?

**Comment by bcomnes** [comment]
```
bret-netlify:choo-test-app bret$ yarn why on-performance
yarn why v1.6.0
(node:22310) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] 🤔  Why do we have the module "on-performance"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "on-performance@1.2.1"
info Reasons this module exists
   - "choo-devtools" depends on it
   - Hoisted from "choo-devtools#on-performance"
   - Hoisted from "choo-devtools#choo-hooks#on-performance"
info Disk size without dependencies: "28MB"
info Disk size with unique dependencies: "72MB"
info Disk size with transitive dependencies: "72MB"
info Number of shared dependencies: 2
✨  Done in 0.68s.
```

It's something throwing from inside of choo-devtools.  Workaround is to disable choo devtools, but we should get that fixed asap.

**Comment by goto-bus-stop** [comment]
Fixed in :package: on-performance 1.2.2
